### ISSUE TITLE
DSX desktop hanging and never installing Notebooks or R studio

### ISSUE THREAD

**Issue by rsickinger** [IBMDataScience/DSx-Desktop#15]
DSX desktop hanging and never installing Notebooks or R studio.  It just hangs at 0 % . I let it go for 30 mins or so and no progress .  Any suggestions

**Comment by Debbani** [comment]
@rsickinger What OS are you on? Please can you attach your log file so that we can diagnose the issue that you're running into.

**Comment by rsickinger** [comment]
Hi,

I am on WIndows 7 .  I originally installed last week and it looked like
everything installed OK.  After install I turned off my computer and didn't
use it.  I tried to use it a couple of times after that and it kept asking
me to install Notebooks and R studio again  and it would never download.  I
un-installed everything  and tied re-installing  yesterday.  Still no
download.  I've attached two logs.  The initial log is desktop2.  And the
new log  is just desktop.

(See attached file: dsx-desktop.log)(See attached file: dsx-desktop2.log)

THanks,
Bob
                                                                                        
                                                                                        
                                                                                        
 Bob Sickinger                                                                          
 Technical Specialist                                                                   
 Analytics, IBM US,                                                                     
 Financial Services Market East                                                         
                                                                                        
                                                                                        
                                                                                        
 Phone: 401-524-5496                                                                    
 E-mail: rsickinger@us.ibm.com                                                          
                                                                                        
                                                                                        
                                                                                        
                                                                                        
                                                                                        
                                                                                        
                                                                                        
                                                                                        










From:	Debbani <notifications@github.com>
To:	IBMDataScience/DSx-Desktop <DSx-Desktop@noreply.github.com>
Cc:	rsickinger <rsickinger@us.ibm.com>, Mention
            <mention@noreply.github.com>
Date:	06/06/2017 03:34 AM
Subject:	Re: [IBMDataScience/DSx-Desktop] DSX desktop hanging and never
            installing Notebooks or R studio (#15)



@rsickinger What OS are you on? Please can you attach your log file so that
we can diagnose the issue that you're running into.


—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or mute the thread.

**Comment by nmarkey10** [comment]
@rsickinger It looks like one of two things is happening, causing the same issue.  Either the path to the Docker Toolbox.exe isn't being stored in your path environment variable or our app is losing track of where it's at.  Our install procedure was overhauled recently which spawned this bug.  I have added a fix for a related error but it isn't out in the latest build yet.  The newer version will be out within the week.  You should be able to uninstall and reinstall if you have "Docker Toolbox" installed, and the path to the exe is inside your path environment variable.  This can be checked by running "echo %PATH%" inside of a command prompt.

**Comment by rsickinger** [comment]
I uninstalled all components , deleted all folders and reinstalled and it is working now. 

Thanks,
Bob

**Comment by nmarkey10** [comment]
@rsickinger awesome!  Glad to hear it.  Sounds like it's related to what I suspected.  Thank you for reporting back!

**Comment by Debbani** [comment]
@rsickinger Closing this issue, please reopen if your problem persists.

**Comment by iAmLipun** [comment]
It's falling to install IBM DSX Desktop as I have installed docker( Version: 18.06.0-ce).but still facing some issue with installing.

tried steps::- I had pulled the hello-world service from docker.

```
PS C:\Users\radia> docker pull hello-world
Using default tag: latest
latest: Pulling from library/hello-world
e46172273a4e: Pull complete
c012fa86f9e5: Pull complete
966bb4253d0f: Pull complete
4116cac73a40: Pull complete
Digest: sha256:4b8ff392a12ed9ea17784bd3c9a8b1fa3299cac44aca35a85c90c5e3c7afacdc
Status: Downloaded newer image for hello-world:latest
```
Also, I had set the environment variable as HTTP_PROXY:- "http://username:password@proxy:port/

but facing some issue with restart service...

PS C:\Users\radia> Restart-Service docker
Restart-Service : Service 'Docker Engine (docker)' cannot be stopped due to the following error: Cannot open docker service on computer '.'.
At line:1 char:1
+ Restart-Service docker
+ ~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : CloseError: (System.ServiceProcess.ServiceController:ServiceController) [Restart-Service], ServiceCommandException
    + FullyQualifiedErrorId : CouldNotStopService,Microsoft.PowerShell.Commands.RestartServiceCommand
Error am getting from installing DSX:-- Did not finish pulling hybridcloudibm/dsx-desktop:ana27spark

Error Logs:-

Error Log
Did not finish pulling hybridcloudibm/dsx-desktop:ana27spark
[2018-08-12 20:42:38:0795] [debug] -- dockerDaemonReady: Docker Daemon is running.
[2018-08-12 20:42:38:0795] [debug] << dockerDaemonReady: dockerConfirm(true)
[2018-08-12 20:42:38:0800] [info] Starting docker...
[2018-08-12 20:42:39:0553] [info] Docker started
[2018-08-12 20:42:39:0571] [info] No current hybridcloud image for DSX Desktop
[2018-08-12 20:42:39:0572] [info] Starting to pull hybridcloudibm/dsx-desktop:core
[2018-08-12 20:42:39:0574] [info] No current hybridcloud image for Anaconda + Spark (Python 2.7, Scala, R)
[2018-08-12 20:42:39:0574] [info] Starting to pull hybridcloudibm/dsx-desktop:ana27spark
[2018-08-12 20:42:46:0784] [error] Stopped pulling hybridcloudibm/dsx-desktop:core with error: image operating system "linux" cannot be used on this platform
[2018-08-12 20:42:46:0836] [info] Did not finish pulling hybridcloudibm/dsx-desktop:ana27spa

**Comment by jerry1100** [comment]
Answered in https://github.com/IBMDataScience/DSx-Desktop/issues/76#issuecomment-414554957.

@iAmLipun please avoid posting on closed issues.
