### ISSUE TITLE
Cannot install DSX in Windows 10 

### ISSUE THREAD

**Issue by gmichel-SMU** [IBMDataScience/DSx-Desktop#2]
I am trying to install DSX Desktop in Windows 10 (Education license). I am running Docker community edition and DSX installation is stalling at 18% and no error message.

How can we check the installation log?
How can we specify installation destination?
Can we download a complete offline installation package instead of live installation?

**Comment by nmarkey10** [comment]
Most of the long pauses during the "Downloading and Writing files" stage of the install are due to the image pulls.  We are pulling multiple large images in parallel and every so often the installer pauses once a layer is pulled.  To look at your log files you can go to this path:  %appdata%\ibm-dsx-desktop\Logs

**Comment by Debbani** [comment]
@gmichel-SMU Please download the latest version of DSX Desktop from: http://datascience.ibm.com/desktop after you've uninstalled DSX Desktop from the Settings. We've addressed many issues in this version.

**Comment by Debbani** [comment]
@gmichel-SMU The latest version (1.1.4) allows you to specify an installation folder where you can download the tars to, and complete the installation offline. You may download the anaconda tar from:
http://dsx-private-cloud.mybluemix.net/downloads/ibm-dsx-ana27.tar.gz/v3.

Please reopen this issue if you continue to run into issues.
