### ISSUE TITLE
SparkContext undefined

### ISSUE THREAD

**Issue by romeokienzler** [IBMDataScience/DSx-Desktop#24]
in a python jupyther notebook I've put that code:

`

`rdd = sc.parallelize([1,2,3])`

The answer is:

> ---------------------------------------------------------------------------
> NameError                                 Traceback (most recent call last)
> <ipython-input-1-a3e688ca42fa> in <module>()
> ----> 1 rdd = sc.parallelize([1,2,3])
> 
> NameError: name 'sc' is not defined
> 

I thought there is support for Spark in DSX Local? Am I wrong?

`

**Comment by romeokienzler** [comment]
Just noticed that there exists two promising kernels, one is called spylon and one is Toree. Spylon works but only if you put Scala into the cells, not python. And Toree doesn't work at all...only getting "dead kernel"

**Comment by sahilshah2211** [comment]
Hi Romeo. For DSX-Desktop, you will need to use Anaconda with Spark installation in order to be able to use local spark and then you will need to create a SparkContext so that you can execute spark code in the notebooks...For example:   
```
from pyspark import SparkContext
from pyspark.sql import SQLContext
sc = SparkContext.getOrCreate()
rdd = sc.parallelize([1,2,3])
```
Also the dead kernel appears because of memory constraints placed by Docker on the containers.  So opening many notebooks at a same time and closing them without shutting the ipython kernel down uses container memory. You Should shut down kernel when you don't use the notebooks. Please refer our documentation for the steps...   
https://datascience.ibm.com/docs/content/desktop/troubleshoot.html

**Comment by romeokienzler** [comment]
awesome, thanks a lot, it works. Was confused since in DSX in the cloud sc is already defined.

**Comment by romeokienzler** [comment]
If u need sparksession this code works

from pyspark import SparkContext
from pyspark.sql import SQLContext
from pyspark.sql import SparkSession
sc = SparkContext.getOrCreate()
spark = SparkSession(sc)

**Comment by stevemart** [comment]
Thanks for adding that code block @romeokienzler -- technically `from pyspark.sql import SQLContext` isn't needed for the other lines to run, but it helped me get past my problem. Thanks!

**Comment by romeokienzler** [comment]
Thanks @stevemart for pointing this out, I've updated my comment accordingly
