### ISSUE TITLE
Accessing Cloudant/ApacheCouchDB doesn't work

### ISSUE THREAD

**Issue by romeokienzler** [IBMDataScience/DSx-Desktop#30]
Accessing Cloudant from DSX Public works fine, but not from DSX Desktop, neither of the following three options works

Option 1 from DSX Documentation
https://developer.ibm.com/clouddataservices/docs/ibm-data-science-experience/docs/load-and-filter-cloudant-data-with-spark/

Option 2-3 taken from my Stackoverflow Thread
https://stackoverflow.com/questions/45207011/how-to-connect-to-cloudand-couchdb-using-sparksql-in-datascience-experience

**Comment by romeokienzler** [comment]
Played around a bit more and wanted to go for the bahir solution end ended up in JAR hell, please have a look at my [notebook](https://gist.github.com/romeokienzler/7b9b538d76ed7db44002ac71d5b3f201)...

**Comment by prashant182** [comment]
Hey Romeo,
Thanks for pointing out your problem. I work with the dsx-desktop team, I can certainly help you with the issue.

**Comment by romeokienzler** [comment]
Hi, I've found the following [solution](https://gist.github.com/romeokienzler/acdd5b21baf19c95339400d5a05a1597) to be working for me, can you please tell me if it is ok to do so? Otherwise I'll stick with yours...

**Comment by romeokienzler** [comment]
@prashant182 please append a GIST of the working copy, so that me and the community can benefit from it...

**Comment by prashant182** [comment]
Hey Romeo, 
I saw the solution you posted earlier. I still think that using `/usr/local/spark-2.1.0-bin-hadoop2.7/` instead of `$SPARK_HOME` is incorrect as we have a different spark path in our environment. Anyways if it is working for you, I am glad it worked out. Please take a look at the [code](https://gist.github.com/prashant182/7fe362f5e8258ed39f80f179f8f2652e) here and let me know.
