### ISSUE TITLE
Internet connection needed during downloading notebook 

### ISSUE THREAD

**Issue by yccheung** [IBMDataScience/DSx-Desktop#39]
I am using a proxy to access the internet and during the installation, no internet connection can be detected. How to set the proxy for the installation?

Thanks for the attention~

**Comment by sahilshah2211** [comment]
@yccheung Please can you verify that the problem still persists in the latest DSX Desktop version. Also if it does it will be really helpful if you can send us the logs. You can find it at `Help -> Open Log Folder`

**Comment by anougo** [comment]
I have the same problem.
I installed Docker for Windows in advance. And could not download notebooks.
[dsx-desktop.log](https://github.com/IBMDataScience/DSx-Desktop/files/1871186/dsx-desktop.log)

**Comment by jerry1100** [comment]
Hi @yccheung, when you say "during the installation, no internet connection can be detected", does the installation fail and that error message is displayed? Or does the download hang forever?

@anougo, this line from your logs:
```
[2018-04-03 19:35:18:0298] [error] Error while pulling hybridcloudibm/dsx-desktop:ana35:
Error: (HTTP code 500) server error - {"message":"Get https://registry-1.docker.io/v2/:
net/http: request canceled while waiting for connection (Client.Timeout exceeded while
awaiting headers)"}
```
indicates that docker could not connect to the public registry. This means the issue is with docker and your proxy, not with DSX Desktop. To verify, open a terminal and enter `docker pull hello-world`. This should fail as well.

I'm not too familiar with configuring docker to use proxies, but I found [this article by Microsoft](https://docs.microsoft.com/en-us/virtualization/windowscontainers/manage-docker/configure-docker-daemon#proxy-configuration) which has some steps on configuring your proxy.

Let me know if that works.

**Comment by anougo** [comment]
@jerry1100, Thank you for your reply.
As you pointed out, `docker pull hello-world` was failed.
After configuring the proxy to Docker for Windows, installer no longer outputs error messages.

**Comment by jerry1100** [comment]
@yccheung, please let me know if this is still an issue for you.
