### ISSUE TITLE
DSX Desktop Installation Fail on Windows

### ISSUE THREAD

**Issue by uedan1** [IBMDataScience/DSx-Desktop#66]
Hi,
I have problems installing DSX Desktop on my Windows laptop. When I have run IBM_DSX_Desktop-1.2.3.exe, I got the following Error Message after "Starting Docker...   100%".

[ErrorLog.txt](https://github.com/IBMDataScience/DSx-Desktop/files/1946080/ErrorLog.txt)

**Comment by jerry1100** [comment]
Hi @uedan1, thanks for posting. What operating system are you running?

**Comment by jerry1100** [comment]
Also, if you don't mind, could you please post the full logs? After opening DSX Desktop, on the title bar: "Help > Open log folder", then upload dsx-desktop.log.

**Comment by uedan1** [comment]
Hi  jerry1100, thank you for your quick response.
Windows7 Professional is running on my laptop.
I attached the dsx-desktop.log. Please refer to the attached file.

[dsx-desktop.zip](https://github.com/IBMDataScience/DSx-Desktop/files/1949253/dsx-desktop.zip)

**Comment by jerry1100** [comment]
For some reason, it seems that the docker machine is not being created. Other than that, the logs don't really say much. Could you briefly list down what happened before you got stuck?

**Comment by jerry1100** [comment]
Hmm, I haven't seen that error before. I did a quick search and found some other [issues on GitHub](https://github.com/docker/machine/issues/4066), but nothing conclusive.

It seems like the issue is with Docker Toolbox and Virtualbox, not so much DSX Desktop. To troubleshoot, try the following:
1. Open a command prompt and enter `docker-machine ls`. This brings up a list of docker machines. If you see `ibm-dsx`, remove it with `docker-machine rm -f ibm-dsx`.
2. Try to create a new machine with `docker-machine create foobar`. I expect this to fail with the same error you posted above. If it succeeds, you can skip the next step.
3. If the above does indeed fail, try installing the latest version of VirtualBox (5.2.10). Then reboot your computer and try step 2 again.

Let me know what you come up with.

**Comment by uedan1** [comment]
Hi jerry1100, thank you for your troubleshoot action.
As my VirtualBox's version was "5.2.8 r121009 (Qt5.6.2)", I uninstalled this and installed "5.2.10 r122406 (Qt5.6.2)". Then reboot my computer.

Here are the results of trouble shooting.
1. I didn't see "ibm-dsx".
2. As you had expected, there was the error.
![troubleshoot_20180509](https://user-images.githubusercontent.com/20895787/39801740-27e6cccc-53a7-11e8-973e-8dce92355f68.png)

**Comment by uedan1** [comment]
Sorry, I closed by mistake.
So, I reopened.

**Comment by jerry1100** [comment]
Based off this [forum post](https://forums.virtualbox.org/viewtopic.php?f=6&t=83287), it seems like it might be a side-effect of a security feature by VirtualBox called "hardening".

Could you please post the hardening log at `C:\Users\IBM_ADMIN\.docker\machine\machines\foobar\foobar\Logs\VBoxHardening.log`?

**Comment by uedan1** [comment]
Please refer this hardening log.
[VBoxHardening.log](https://github.com/IBMDataScience/DSx-Desktop/files/1990191/VBoxHardening.log)

**Comment by jerry1100** [comment]
Unfortunately, I had no luck reading that log.

Are you able to reproduce this issue on another machine?

**Comment by uedan1** [comment]
Sorry for my late reply.　I made this file with Unicode. Please try this.
[VBoxHardening.log.txt](https://github.com/IBMDataScience/DSx-Desktop/files/2046674/VBoxHardening.log.txt)

**Comment by jerry1100** [comment]
I meant I couldn't find anything helpful in the logs, not that I couldn't open them.

Are you able to reproduce the issue on a different machine?

**Comment by jerry1100** [comment]
@uedan1 just following up, is this still an issue?

**Comment by uedan1** [comment]
thank you for your attention. Please finish to follow this issue.
