### ISSUE TITLE
Deprecated Spark functions in Spark for R.ipynb 

### ISSUE THREAD

**Issue by cabarendt** [IBMDataScience/DSx-Desktop#9]
First two Spark APIs in this Tutorial Notebook generated Deprecated Warning messages:

(1) library(SparkR)
sc <- sparkR.session()
sqlContext <- sparkRSQL.init(sc)

**Warning message:**
“'sparkRSQL.init' is deprecated.
Use 'sparkR.session' instead.
See help("Deprecated")”

(2) sdf <- createDataFrame(sqlContext, mtcars) 
printSchema(sdf)

**Warning message:**
“'createDataFrame(sqlContext...)' is deprecated.
Use 'createDataFrame(data, schema = NULL)' instead.
See help("Deprecated")”

**Comment by sahilshah2211** [comment]
@cabarendt Accoding to ` https://stackoverflow.com/questions/46434647/how-to-resolve-sqlsqlcontext-is-deprecated-warning-in-sparkr`,  since Spark 2.0 sql and the number of other functions (like createDataFrame) dont require SQLContext instance. Internally this will use getSparkSession to retrieve a session object.

**Comment by jerry1100** [comment]
Closing since it's been almost a year. Please reopen if needed.
